config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  resources :users
  resources :invitations, except: [:edit, :update]
  post '/invitations/table', to: 'invitations#table'

  resources :parcelles
  resources :parcelle do
    resources :comments, only: [:new, :create]
  end
  post '/parcelles/table', to: 'parcelles#table'
  get '/carte', to: 'parcelles#carte', as: :carte

  resources :comments, except: [:new, :create]

  resources :tags
  post '/tags/table', to: 'tags#table'

  resources :suppliers
  resources :supplier do
    resources :offers, only: [:new, :create]
  end
  post '/suppliers/table', to: 'suppliers#table'

  resources :offers, except: [:new, :create]
  post '/offers/table', to: 'offers#table'

  get '/mapbox_token', to: 'maps#token', as: :mapbox_token
end

app/views/shared/_account.html.erb
<account-status>
  <% unless user_signed_in? %>
    <%= link_to "connexion", new_user_session_path %>
  <% end %>
</account-status>
<li-dropdown>
  <%= render partial: 'shared/avatar', locals: { user: current_user, width: '50px' } %>
  <account-connexion data-controller='connexion'
                     data-connexion-status-value='<%= user_signed_in? %>'
                     data-connexion-target='circle'
  >
  </account-connexion>
    <ul>
      <%= link_to 'mon compte', edit_user_registration_path(current_user), data: { navbar_target: 'link'} %>
      <% if user_signed_in? %>
        <%= link_to 'mes invitations envoyées', invitations_path(users: :guests), data: { navbar_target: 'link'} %>
        <%= link_to 'mes invitations reçues', invitations_path(users: :owners), data: { navbar_target: 'link'} %>
        <%= link_to "déconnexion", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% end %>
    </ul>
</li-dropdown>

app/views/shared/_avatar.html.erb
<% if user %>
  <% if user.avatar.attached? %>
    <%= cl_image_tag user.avatar.key, transformation: [{ height: 45, width: 45, crop: 'thumb', gravity: 'face'}], class: 'avatar' %>
  <% else %>
    <%= image_tag 'user.png', width: width %>
  <% end %>
<% else %>
  <%= image_tag 'user.png', width: width %>
<% end %>

app/views/shared/_comment.html.erb
<comment-wrapper data-controller='comment'>
  <comment-1>
    <%= render partial: 'shared/avatar', locals: { user: comment.user, width: '40px' } %>
  </comment-1>
  <comment-2>
    <% if option == :new %>
      <%= turbo_frame_tag 'new_comment' do %>
        <%= link_to 'Rédiger un commentaire ... ', new_parcelle_comment_path(@parcelle) %>
      <% end %>
    <% end %>

    <% if option == :show %>
      <comment-info>
        <comment-email>
          <%= comment.user.email %>
        </comment-email>
        <comment-date>
          <%= comment.created_at.strftime("le %d-%m-%Y à %H:%M") %>
        </comment-date>
      </comment-info>
      <%= turbo_frame_tag comment do %>
        <%= comment.content %>
        <% if allowed_to?(:edit?, comment) %>
          <%= link_to 'modifier', edit_comment_path(comment) %>
        <% end %>
        <% if allowed_to?(:destroy?, comment) %>
          <%= link_to 'supprimer', comment_path(comment), data: { turbo_method: :delete, turbo_frame: 'comments' } %>
        <% end %>
        <%= render partial: 'shared/gallery', locals: { comment: comment } %>
      <% end %>
    <% end %>
  </comment-2>
</comment-wrapper>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <ul id="error_explanation" data-turbo-cache="false">
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
      <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>

  </ul>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <section>
    <h1>
      A propos
    </h1>
    <ul>
      <%= link_to '', 'https://github.com/RaphaelAubry', class: "fa-brands fa-github" %>
    </ul>
  </section>
  <section>
    <h1>
      Support
    </h1>
    <ul>
      <li>
        <h2>
          <%= mail_to ApplicationMailer.default[:from], "Contact" %>
        </h2>
      </li>
    </ul>
  </section>
  <section>
    <h1>
      Ressources
    </h1>
    <ul>
      <li>
        <h2>
          <%= link_to 'Mapbox', 'https://www.mapbox.com/' %>
        </h2>
      </li>
      <li>
        <h2>
          <%= link_to 'IGN - API Carto', 'https://apicarto.ign.fr/api/doc/' %>
        </h2>
      </li>
      <li>
        <h2>
          <%= link_to 'API Gouv', 'https://api.gouv.fr/les-api/base-adresse-nationale' %>
        </h2>
      </li>
    </ul>
  </section>
</footer>

app/views/shared/_gallery.html.erb
<gallery-wrapper>
  <% if comment.present? %>
    <% comment.images.each do |image| %>
      <gallery-image data-controller="image">
        <%= cl_image_tag image.key,
          crop: "fill",
          class: 'gallery-image',
          data: { action: 'click->image#fullscreen' }
        %>
        <% if allowed_to?(:edit?, comment) %>
          <%= link_to 'supprimer', comment_path(comment, params: { attachment_id: image.id, cloudinary_key: image.key }),
            data: { turbo_method: :delete, turbo_frame: 'comments' }
          %>
        <% end %>
      </gallery-image>
    <% end %>
  <% end %>
<gallery-wrapper>

app/views/shared/_messages.html.erb
<% flash.each do |key, message| %>
  <message-wrapper id="flash" class='<%= key %>'>
    <message-content>
      <%= message %>
    </message-content>
    <fa-xmark class="fa-solid fa-xmark"></fa-xmark>
  </message-wrapper>
<% end %>

app/views/shared/_navbar.html.erb
<container-navbar data-controller='navbar' data-controller='window'>
  <navbar-logo>
    <%= image_tag 'Gestion Parcelles Logo 1.png', width: '40px', height: '40px' %>
  </navbar-logo>
  <navbar-icon data-action='click->navbar#displayMenu'>
    <%= image_tag 'Gestion Parcelles Logo 1.png', width: '40px', height: '40px' %>
  </navbar-icon>
  <navbar-menu data-navbar-target='menu' data-window-target='menu'>
    <ul>
      <li><%= link_to :home, root_path, data: { navbar_target: 'link'} %></li>
      <% if user_signed_in? %>
        <li><%= link_to :carte, carte_path, data: { navbar_target: 'link'} %></li>
        <li-dropdown>tableaux
          <ul>
            <%= link_to 'mes parcelles', parcelles_path, data: { navbar_target: 'link'} %>
            <%= link_to :fournisseurs, suppliers_path, data: { navbar_target: 'link'} %>
            <%= link_to :prestations, offers_path, data: { navbar_target: 'link'} %>
            <% current_user.owners.each do |owner| %>
              <%= link_to owner.email, parcelles_path, data: { navbar_target: 'link' } %>
            <% end %>
          </ul>
        </li-dropdown>
      <% end %>
    </ul>
  </navbar-menu>

  <navbar-account data-navbar-target='menu'>
    <p><%= current_user.email if user_signed_in? %></p>
    <%= render 'shared/account' %>
  </navbar-account>
</container-navbar>

app/views/shared/_table.html.erb
<%# deprecated %>

<% if instances.present? %>
  <table>
    <%= render partial: 'shared/table/1_header', locals: { instances: instances,
                                                           controller: controller,
                                                           columns: options[:columns],
                                                           tag_show: options[:tag_show],
                                                           tool_show: options[:tool_show]
                                                         }


    %>
      <tbody>
        <% instances.each do |instance| %>
          <tr id="<%= instance.model_name.singular %>_<%= instance.id %>"
              data-controller="row"
              href="<%= send("#{instance.model_name.singular}_path", instance) %>"
          >
            <%= render partial: 'shared/table/2_row', locals: { instance: instance,
                                                                controller: controller,
                                                                columns: options[:columns],
                                                                link_show: options[:link_show],
                                                                tag_show: options[:tag_show],
                                                                tool_show: options[:tool_show]
                                                              }
            %>
          </tr>
        <% end %>
      </tbody>
    <%= render partial: 'shared/table/3_footer', locals: { instances: instances,
                                                           columns: options[:columns],
                                                           formulas: options[:formulas]
                                                         }
    %>
  </table>
<% else %>
  <%= 'Aucun élément à afficher' %>
<% end %>

app/views/shared/_tag.html.erb
  <tag-box data-controller="tag" data-tag-target="box" data-color=<%= color %>>
  </tag-box>