config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  resources :users
  resources :invitations, except: [:edit, :update]
  post '/invitations/table', to: 'invitations#table'

  resources :parcelles
  resources :parcelle do
    resources :comments, only: [:new, :create]
  end
  post '/parcelles/table', to: 'parcelles#table'
  get '/carte', to: 'parcelles#carte', as: :carte

  resources :comments, except: [:new, :create]

  resources :tags
  post '/tags/table', to: 'tags#table'

  resources :suppliers
  resources :supplier do
    resources :offers, only: [:new, :create]
  end
  post '/suppliers/table', to: 'suppliers#table'

  resources :offers, except: [:new, :create]
  post '/offers/table', to: 'offers#table'

  get '/mapbox_token', to: 'maps#token', as: :mapbox_token
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :owner, foreign_key: 'owner_id', class_name: 'User'
  belongs_to :guest, foreign_key: 'guest_id' , class_name: 'User'

  validates :guest, uniqueness: { scope: :owner, message: 'déjà convié' }
  validate :dont_invite_yourself

  CONFIG = { link: { guests: false, owners: true } }

  def dont_invite_yourself
    if guest.email == owner.email
      errors.add(:mail, 'vous avez saisi votre propre adresse email, choisissze l\'adresse de votre invité')
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :user

  def index
    @invitations = authorized_scope(User, type: :relation, as: params[:users].to_sym, scope_options: { user: current_user }, with: UserPolicy)

    @link = Invitation::CONFIG[:link][params[:users].to_sym]

    respond_to do |format|
      format.html
      format.json { render json: @invitations }
    end
  end

  def table
    if params[:order]
      order = params[:order]["0"][:name].present? ? params[:order]["0"][:name] + " " + params[:order]["0"][:dir].upcase : ""
    end

    @invitations = authorized_scope(User, type: :relation, as: params[:invitation_users].to_sym, scope_options: { user: current_user }, with: UserPolicy)

    @invitations = @invitations.tap { |x| @total_count = x.count }
                               .where("name LIKE ?", "%#{params[:search][:value]}%")
                               .or(@invitations.where("surname LIKE ?", "%#{params[:search][:value]}%"))
                               .or(@invitations.where("phone::TEXT LIKE ?", "%#{params[:search][:value]}%"))
                               .or(@invitations.where("email LIKE ?", "%#{params[:search][:value]}%"))
                               .or(@invitations.where("invitations.created_at::TEXT LIKE ?", "%#{params[:search][:value]}%"))
                               .order(order)
                               .tap { |x| @filtered_count = x.count }
                               .select('users.name, users.surname, users.phone, users.email, invitations.created_at as created_at, invitations.id as id')
                               .limit(params[:length])
                               .offset(params[:start])

    respond_to do |format|
      format.json do
        render json: {
          draw: params[:draw],
          recordsTotal: @total_count,
          recordsFiltered: @filtered_count,
          data: @invitations.map do |i|
                              [ i.name,
                                i.surname,
                                i.phone,
                                i.email,
                                l(i.created_at, format: :short),
                                "
                                <a href='/invitations/#{i.id}' data-turbo-method='delete'>supprimer</a>
                                "
                              ]
                            end
          }
      end
    end


  end

  def new
    authorize! @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new
    @guest = User.find_by(email: params[:invitation][:guest_email])

    if @guest
      authorize! @invitation = Invitation.create(owner: @user, guest: @guest)

      if @invitation.save
        InvitationMailer.with(user: @user, guest: @invitation.guest).notify_create_guest.deliver_now

        respond_to do |format|
          format.html { redirect_to invitations_path(users: :guests), notice: "Invité(e) enregistré(e)" }
        end
      else
        render :new, status: :unprocessable_entity
      end
    else
      @invitation.errors.add :guest, :not_found, message: 'adresse email introuvable, votre invité doit s\'inscrire'
      InvitationMailer.with(user: @user, mail: params[:invitation][:guest_email]).invite.deliver_now
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @invitation = Invitation.find(params[:id])

    authorize! @invitation, with: InvitationPolicy

    @invitation.destroy

    if @user == @invitation.owner
      InvitationMailer.with(user: @user, guest: @invitation.guest).notify_destroy_guest.deliver_now
    end

    if @user = @invitation.guest
      InvitationMailer.with(user: @invitation.owner, guest: @user).notify_destroy_owner.deliver_now
    end

    respond_to do |format|
      format.html { redirect_to invitations_path(users: :guests), notice: "Invité(e) supprimé(e) avec succès" }
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:guest_id, :owner_id)
  end

  def user
    @user = current_user
  end
end

app/views/invitations/_form.html.erb
<%= form_for @invitation do |form| %>
  <%= render 'shared/error_messages', resource: @invitation %>

  <input-group data-controller='input-group'>
    <%= form.label 'invité', data: { input_group_target: 'label' }

    %>
    <%= form.email_field :guest_email,
        value: '',
        data: { input_group_target: 'input',
                action: 'focus->input-group#focusLabel
                      focusout->input-group#focusoutLabel
                      change->input-group#focusLabel'
              }
    %>
  </input-group>
  <submit-group>
    <%= form.submit 'valider', class: 'button' %>
    <%= link_to :annuler, :back %>
  </submit-group>
<% end %>

app/views/invitations/_table.html.erb
<table data-controller="datatable" data-datatable-name-value="invitations">
  <thead>
    <tr>
      <% columns.each do |column| %>
        <th><%= t(column) %></th>
      <% end %>
    </tr>
  <thead>
</table>

app/views/invitations/edit.html.erb
<link-group>
  <%= link_to t(:back), :back %>
</link-group>

app/views/invitations/index.html.erb
<container-tableau>
  <%= render partial: 'table', locals: { instances: @invitations,
                                        columns: %i(name surname phone email created_at),
                                      }
  %>
  <link-group>
    <%= link_to 'inviter', new_invitation_path %>
  </link-group>
</container-tableau>

app/views/invitations/new.html.erb
<wrapper-form>
  <h3>Nouvelle Invitation</h3>
  <%= render 'form', user: @user %>
</wrapper-form>