config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  resources :users
  resources :invitations, except: [:edit, :update]
  post '/invitations/table', to: 'invitations#table'

  resources :parcelles
  resources :parcelle do
    resources :comments, only: [:new, :create]
  end
  post '/parcelles/table', to: 'parcelles#table'
  get '/carte', to: 'parcelles#carte', as: :carte

  resources :comments, except: [:new, :create]

  resources :tags
  post '/tags/table', to: 'tags#table'

  resources :suppliers
  resources :supplier do
    resources :offers, only: [:new, :create]
  end
  post '/suppliers/table', to: 'suppliers#table'

  resources :offers, except: [:new, :create]
  post '/offers/table', to: 'offers#table'

  get '/mapbox_token', to: 'maps#token', as: :mapbox_token
end

app/models/tag.rb
class Tag < ApplicationRecord
  include FilterModelConcern

  belongs_to :user
  has_many :parcelles, dependent: :nullify

  validates :name, uniqueness: { scope: :user, message: 'Nom déjà utilisé' }

  scope :parcelles_from_batch, ->(parcelles) { joins(:parcelles).where(parcelles: parcelles ) }
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :user

  def index
    authorize! @tags = authorized_scope(Tag, type: :relation, as: :access, scope_options: { user: current_user })
    authorize! @user = current_user, to: :edit?, with: UserPolicy

    respond_to do |format|
      format.html
      format.json { render json: @tags }
    end
  end

  def table
    if params[:order]
      order = params[:order]["0"][:name].present? ? params[:order]["0"][:name] + " " + params[:order]["0"][:dir].upcase : ""
    end

    authorize! @tags = authorized_scope(Tag, type: :relation, as: :access, scope_options: { user: current_user })

    @tags = @tags.tap { |x| @total_count = x.count }
                 .where("name LIKE ?", "%#{params[:search][:value]}%")
                 .or(@tags.where("description LIKE ?", "%#{params[:search][:value]}%"))
                 .or(@tags.where("color LIKE ?", "%#{params[:search][:value]}%"))
                 .order(order)
                 .tap { |x| @filtered_count = x.count }
                 .limit(params[:length])
                 .offset(params[:start])

    respond_to do |format|
      format.json do
        render json: {
          draw: params[:draw],
          recordsTotal: @total_count,
          recordsFiltered: @filtered_count,
          data: @tags.map do |t|
                  [ t.name,
                    t.description,
                    "<td-tag>
                      <tag-box data-controller='tag' data-tag-target='box' data-color='#{t.color}'>
                      </tag-box>
                    </td-tag>
                    ",
                    "<a href='/tags/#{t.id}/edit'>modifier</a>
                     <a href='/tags/#{t.id}' data-turbo-method='delete'>supprimer</a>
                    "
                  ]
                end
          }
      end
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.create(tag_params)
    @tag.user = @user

    if @tag.save
      respond_to do |format|
        format.html { redirect_to tags_path, notice: "Le marqueur est créé avec succès" }
      end
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    @tag.update(tag_params)

    if @tag.save
      respond_to do |format|
        format.html { redirect_to tags_path, notice: "Le marqueur est modifié avec succès" }
      end
    else
      render edit:, status: :unprocessable_entity
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_path, notice: "Marqueur supprimé avec succès" }
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:name, :description, :color, :user_id)
  end

  def user
    @user = current_user
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag do |form| %>
  <%= render "shared/error_messages", resource: @tag %>
  <input-group data-controller='input-group'>
    <%= form.label 'nom',
      data: { input_group_target: 'label' }
    %>
    <%= form.text_field :name,
      data: { input_group_target: 'input',
              action: 'focus->input-group#focusLabel
                      focusout->input-group#focusoutLabel
                      change->input-group#focusLabel'
            }
    %>
  </input-group>
  <input-group data-controller='input-group'>
    <%= form.label 'description',
      data: { input_group_target: 'label' }
    %>
    <%= form.text_area :description,
      data: { input_group_target: 'input',
              action: 'focus->input-group#focusLabel
                      focusout->input-group#focusoutLabel
                      change->input-group#focusLabel'
            }
    %>
  </input-group>
  <input-group data-controller='input-group'>
    <%= form.label 'couleur',
      data: { input_group_target: 'label' }
    %>
    <%= form.color_field :color,
      data: { input_group_target: 'input',
              action: 'focus->input-group#focusLabel
                      focusout->input-group#focusoutLabel
                      change->input-group#focusLabel'
            }
    %>
  </input-group>

  <submit-group>
    <%= form.submit 'valider', class: 'button' %>
    <%= link_to :annuler, :back %>
  </submit-group>
<% end %>

app/views/tags/_table.html.erb
<table data-controller="datatable" data-datatable-name-value="tags">
  <thead>
    <tr>
      <% columns.each do |column| %>
        <th><%= t(column) %></th>
      <% end %>
    </tr>
  <thead>
</table>

app/views/tags/edit.html.erb
<wrapper-form>
  <h3>Modifier le marqueur : <%= @tag.name %></h3>
  <%= render 'form', tag: @tag %>
</wrapper-form>

app/views/tags/index.html.erb
<container-tableau>
  <h3>Marqueurs</h3>
  <%= render partial: 'table', locals: { columns: [:name, :description, :color] } %>
  <link-group>
    <%= link_to 'nouveau marqueur', new_tag_path, data: { navbar_target: 'link' } %>
  </link-group>
</container-tableau>

app/views/tags/new.html.erb
<wrapper-form>
  <h3>Nouveau marqueur</h3>
  <%= render 'form', tag: @tag %>
</wrapper-form>